class CustomError(Exception):
   pass

raise CustomError

__main__.CustomError
raise CustomeError("An error occured...")